export enum PrepResetPasswordTypes {
    PREP_RESET_PASSWORD_REQUEST = '[PrepResetPassword]PREP_RESET_PASSWORD_REQUEST',
    PREP_RESET_PASSWORD_SUCCESS = '[PrepResetPassword]PREP_RESET_PASSWORD_SUCCESS',
}