export enum FileTypes {
    UPLOAD_FILE_REQUEST = '[FileTypes]UPLOAD_FILE_REQUEST',
    UPLOAD_FILE_SUCCESS = '[FileTypes]UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_ERROR = '[FileTypes]UPLOAD_FILE_ERROR',

    GET_FILES_REQUEST = '[FileTypes]GET_FILES_REQUEST',
    GET_FILES_SUCCESS = '[FileTypes]GET_FILES_SUCCESS',
    GET_FILES_ERROR = '[FileTypes]GET_FILES_ERROR',

    DELETE_FILE_REQUEST = '[FileTypes]DELETE_FILE_REQUEST',
    DELETE_FILE_SUCCESS = '[FileTypes]DELETE_FILE_SUCCESS',
    DELETE_FILE_ERROR = '[FileTypes]DELETE_FILE_ERROR',

    SELECT_FILE = '[FileTypes]SELECT_FILE',
    DELETE_FILES = '[FileTypes]DELETE_FILES',
}
