export enum BlogTypes {
    CREATE_BLOG_REQUEST = '[BlogTypes]CREATE_BLOG_REQUEST',
    CREATE_BLOG_SUCCESS = '[BlogTypes]CREATE_BLOG_SUCCESS',
    CREATE_BLOG_ERROR = '[BlogTypes]CREATE_BLOG_ERROR',

    GET_BLOGS_REQUEST = '[BlogTypes]GET_BLOGS_REQUEST',
    GET_BLOGS_SUCCESS = '[BlogTypes]GET_BLOGS_SUCCESS',
    GET_BLOGS_ERROR = '[BlogTypes]GET_BLOGS_ERROR',

    GET_BLOG_REQUEST = '[BlogTypes]GET_BLOG_REQUEST',
    GET_BLOG_SUCCESS = '[BlogTypes]GET_BLOG_SUCCESS',
    GET_BLOG_ERROR = '[BlogTypes]GET_BLOG_ERROR',

    UPDATE_BLOG_REQUEST = '[BlogTypes]UPDATE_BLOG_REQUEST',
    UPDATE_BLOG_SUCCESS = '[BlogTypes]UPDATE_BLOG_SUCCESS',
    UPDATE_BLOG_ERROR = '[BlogTypes]UPDATE_BLOG_ERROR',

    DELETE_BLOG_PRE_REQUEST = '[BlogTypes]DELETE_BLOG_PRE_REQUEST',
    DELETE_BLOG_REQUEST = '[BlogTypes]DELETE_BLOG_REQUEST',
    DELETE_BLOG_SUCCESS = '[BlogTypes]DELETE_BLOG_SUCCESS',
    DELETE_BLOG_ERROR = '[BlogTypes]DELETE_BLOG_ERROR',

    HUB_UPDATE_BLOG_REQUEST = '[BlogTypes]HUB_UPDATE_BLOG_REQUEST',
    HUB_UPDATE_BLOG_SUCCESS = '[BlogTypes]HUB_UPDATE_BLOG_SUCCESS',
    HUB_CREATE_BLOG_REQUEST = '[BlogTypes]HUB_CREATE_BLOG_REQUEST',
    HUB_CREATE_BLOG_SUCCESS = '[BlogTypes]HUB_CREATE_BLOG_SUCCESS',

    DELETE_BLOGS = '[BlogTypes]DELETE_BLOGS',
    DELETE_CREATED_BLOG = '[BlogTypes]DELETE_CREATED_BLOG',
    DELETE_UPDATED_BLOG = '[BlogTypes]DELETE_UPDATED_BLOG',
}
