export enum ProfileTypes {
    UPDATE_PROFILE_REQUEST = '[SettingsTypes]UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_SUCCESS = '[SettingsTypes]UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR = '[SettingsTypes]UPDATE_PROFILE_ERROR',
    GET_PROFILE_REQUEST = '[SettingsTypes]GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS = '[SettingsTypes]GET_PROFILE_SUCCESS',
    GET_PROFILE_ERROR = '[SettingsTypes]GET_PROFILE_ERROR',
}