export enum ResendConfirmationTypes {
    RESEND_CONFIRMATION_REQUEST = '[ResendConfirmation]RESEND_CONFIRMATION_REQUEST',
    RESEND_CONFIRMATION_SUCCESS = '[ResendConfirmation]RESEND_CONFIRMATION_SUCCESS',
    RESEND_CONFIRMATION_ERROR = '[ResendConfirmation]RESEND_CONFIRMATION_ERROR',
}