export enum AuthTypes {
    SIGNOUT_REQUEST = '[Auth]SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS = '[Auth]SIGNOUT_SUCCESS',
    SIGNOUT_ERROR = '[Auth]SIGNOUT_ERROR',
    SET_AUTHORIZED = '[Auth]SET_AUTHORIZED',
}