export enum SigninTypes {
    SIGNIN_REQUEST = '[Signin]SIGNIN_REQUEST',
    SIGNIN_SUCCESS = '[Signin]SIGNIN_SUCCESS',
    SIGNIN_ERROR = '[Signin]SIGNIN_ERROR',
    RESET_ERROR = '[Signin]RESET_ERROR',
    EXTERNAL_SIGNIN = '[Signin]EXTERNAL_SIGNIN',
}
