export enum SettingsTypes {
    UPDATE_PERSON_REQUEST = '[SettingsTypes]UPDATE_PERSON_REQUEST',
    UPDATE_PERSON_SUCCESS = '[SettingsTypes]UPDATE_PERSON_SUCCESS',
    UPDATE_PERSON_ERROR = '[SettingsTypes]UPDATE_PERSON_ERROR',
}