export enum ResetPasswordTypes {
    RESET_PASSWORD_REQUEST = '[ResetPassword]RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS = '[ResetPassword]RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR = '[ResetPassword]RESET_PASSWORD_ERROR',
    RESET_ERROR = '[ResetPassword]RESET_ERROR',
}